version: '3.7'

services:
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk_net


  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.1
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./shared/logs:/usr/share/logstash/logs:ro 
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
    networks:
      - elk_net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elk_net

  training:
    image: clip-training:latest
    container_name: clip-training
    environment:
      - REGISTRY_DIR=/app/registry
      - MODEL_REGISTRY_DIR=/app/model_registry
      - LOGS_DIR=/app/logs
    volumes:
      - ./shared/registry:/app/registry
      - ./shared/model_registry:/app/model_registry
      - ./shared/final_aug_dataset:/app/final_aug_dataset
      - ./shared/logs:/app/logs
      - ./shared/.cache/clip:/app/.cache/clip
      - ./shared/runs:/app/runs
      - ./training/train.py:/app/train.py 
      - ./training/dataset.py:/app/dataset.py 
      - ./training/main.py:/app/main.py 
      - ./training/model.py:/app/model.py 
      - ./training/test.py:/app/test.py 
      - ./training/utils.py:/app/utils.py 
      - ./training/config_docker.yaml:/app/config_docker.yaml 

    runtime: nvidia 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["python3", "main.py"]
    shm_size: '16g'
    networks:
      - elk_net
  
  inference:
    image: clip-inference:latest
    container_name: clip-inference
    environment:
      - MODEL_REGISTRY_DIR=/app/model_registry
      - FINAL_AUG_DATASET=/app/final_aug_dataset
      - LOG_DIR=/app/logs
      - CLIP_CACHE_DIR=/app/.cache/clip
    volumes:
      - ./shared/model_registry:/app/model_registry
      - ./shared/final_aug_dataset/annotations.csv:/app/final_aug_dataset/annotations.csv
      - ./shared/logs:/app/logs
      - ./shared/.cache/clip:/app/.cache/clip
      - ./web_app/app.py:/app/app.py
    runtime: nvidia 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8502:8502"
    shm_size: '16g'
    networks:
      - elk_net
      
networks:
  elk_net:
    driver: bridge

volumes:
  es_data: